name: journey
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python==3.12.8
  - conda-forge::pandoc
  - conda-forge::graphviz
  - conda-forge::imageio
  - conda-forge::numpy
  - conda-forge::gymnasium
  - conda-forge::matplotlib
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.4
  - pytorch::torchaudio
  - pytorch::torchvision
  - conda-forge::seaborn
  - conda-forge::stable-baselines3
  - conda-forge::tqdm
  - jupyter
  - conda-forge::jupyter-ai
